import Head from 'next/head';
import Image from 'next/image';
import Banner from '../../../libs/coffee-store-shared-components/Banner';
import Card from '../../../libs/coffee-store-shared-components/Card';
import styles from '../styles/Home.module.css';
import { fetchCoffeeStores } from '../lib/coffee-stores';
import useTrackLocation from '../hooks/useTrackLocation';

export async function getStaticProps() {
  const coffeeStores = await fetchCoffeeStores();

  return {
    props: {
      coffeeStores,
    }, //will be passes to the page component as props
  };
}

export default function Home({ coffeeStores }) {
  const { handleTrackLocation, latLong, locationErrorMsg, isFindingLocation } =
    useTrackLocation();

  const handleOnBannerBtnClick = () => {
    console.log('Banner button clicked!');
    handleTrackLocation();
  };

  console.log({
    latlong: latLong,
    errorMsg: locationErrorMsg,
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={isFindingLocation ? 'Loading...' : 'View stores nearby'}
          handleOnClick={() => handleOnBannerBtnClick()}
        />

        {locationErrorMsg && (
          <span>Something went wrong: {locationErrorMsg}</span>
        )}

        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="Coffee"
            width={700}
            height={400}
          />
        </div>

        {coffeeStores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl || '/static/hero-image.png'}
                    href={`/coffee-store/${coffeeStore.id}`}
                    className={styles.card}
                    key={coffeeStore.id}
                  />
                );
              })}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
